### ISSUE TITLE
Look into Chromium headless

### ISSUE THREAD

**Issue by lastmjs** [scramjs/scram-engine#30]
It looks like Chromium has an official headless option now. This might make it easier to user Electron headlessly on operating systems without graphics capabilities, so we could drop the xvfb dependency: https://github.com/electron/electron/issues/228#issuecomment-271176797

**Comment by from-nibly** [comment]
I am in the middle of developing a cli/gui app that needs this. sometimes it runs on a developers laptop and they can use the gui and sometimes it runs in the build server that only has xvfb. In my experience xvfb can be flaky and breaks our builds often. It would be nice to be able to just run electron headlessly in this case.

**Comment by lastmjs** [comment]
All of the under-the-hood implementation for headless is done in main.js, as far as I know how to do it. I don't believe it is working. There has been no official word from Electron on this, so we should probably just wait.

**Comment by lastmjs** [comment]
Should be obsolete in lieu of basicHTML: https://github.com/WebReflection/basicHTML
